#include <stdio.h>

void generate_cursed_viewer() {
    FILE* f = fopen("cursed_viewer.html", "w");
    if (!f) return;

    fprintf(f, 
        "<!DOCTYPE html>\n"
        "<html>\n"
        "<head>\n"
        "  <title>Cursed Real-Time Monitor</title>\n"
        "  <style>\n"
        "    body { background: #0a0a0a; color: #00ff00; font-family: monospace; display: flex; height: 100vh; margin: 0; overflow: hidden; }\n"
        "    #left_pane { flex: 1; padding: 20px; display: flex; flex-direction: column; border-right: 2px dashed #333; max-width: 400px; }\n"
        "    #right_pane { flex: 2; display: flex; align-items: center; justify-content: center; background: #111; padding: 20px; }\n"
        "    \n"
        "    /* The Canvas & Blank State */\n"
        "    #canvas_container { border: 2px solid #00ff00; box-shadow: 0 0 15px #00ff0033; position: relative; display: flex; align-items: center; justify-content: center; min-width: 300px; min-height: 200px; }\n"
        "    img { image-rendering: pixelated; max-width: 100%%; max-height: 90vh; display: none; } /* Hidden by default */\n"
        "    #blank_state { color: #333; font-size: 24px; font-weight: bold; letter-spacing: 5px; animation: pulse 2s infinite; }\n"
        "    \n"
        "    @keyframes pulse { 0%% { opacity: 0.3; } 50%% { opacity: 0.8; } 100%% { opacity: 0.3; } }\n"
        "    \n"
        "    /* The Terminal Logs */\n"
        "    #term_output { flex: 1; overflow-y: auto; background: #000; border: 1px solid #333; padding: 10px; white-space: pre-wrap; font-size: 14px; }\n"
        "    h2 { font-size: 18px; text-transform: uppercase; border-bottom: 1px solid #00ff00; padding-bottom: 10px; }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "\n"
        "  <div id=\"left_pane\">\n"
        "    <h2>> CURSED_ENGINE :: LOG_OUTPUT</h2>\n"
        "    <p style=\"color: #888; font-size: 12px;\">Input commands in your C terminal.</p>\n"
        "    <div id=\"term_output\">Waiting for engine logs...</div>\n"
        "  </div>\n"
        "\n"
        "  <div id=\"right_pane\">\n"
        "    <div id=\"canvas_container\">\n"
        "      <div id=\"blank_state\">&lt; BLANK &gt;</div>\n"
        "      <img id=\"screen\" alt=\"Engine frame\">\n"
        "    </div>\n"
        "  </div>\n"
        "\n"
        "  <script>\n"
        "    const screen = document.getElementById('screen');\n"
        "    const blankState = document.getElementById('blank_state');\n"
        "    const term = document.getElementById('term_output');\n"
        "    \n"
        "    window.updateTerm = function(text) {\n"
        "        if (term.textContent !== text) {\n"
        "            term.textContent = text;\n"
        "            term.scrollTop = term.scrollHeight;\n"
        "        }\n"
        "    };\n"
        "    \n"
        "    function pollEngine() {\n"
        "      let t = new Date().getTime();\n"
        "      \n"
        "      /* 1. Image Polling with Fallback */\n"
        "      let imgLoader = new Image();\n"
        "      imgLoader.onload = function() {\n"
        "          screen.src = imgLoader.src;\n"
        "          screen.style.display = 'block';\n"
        "          blankState.style.display = 'none';\n"
        "      };\n"
        "      imgLoader.onerror = function() {\n"
        "          screen.style.display = 'none';\n"
        "          blankState.style.display = 'block';\n"
        "      };\n"
        "      imgLoader.src = 'temp_export.png?t=' + t;\n"
        "      \n"
        "      /* 2. Log Polling via Script Injection */\n"
        "      let script = document.createElement('script');\n"
        "      script.src = 'cursed_log.js?t=' + t;\n"
        "      script.onload = () => script.remove();\n"
        "      script.onerror = () => script.remove();\n"
        "      document.head.appendChild(script);\n"
        "    }\n"
        "    \n"
        "    setInterval(pollEngine, 100);\n"
        "  </script>\n"
        "</body>\n"
        "</html>\n"
    );
    fclose(f);
    printf("-> Generated 'cursed_viewer.html'.\n");
}